include(ExternalProject)

include(FindPackageHandleStandardArgs)

if(NOT DEPENDENCY_INSTALL_DIR)
    set(DEPENDENCY_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/extdeps)
endif()

# Main loop to install each dependency (includes some hacks for Geant4 config)
add_custom_target( extdeps )
foreach( dependency ${DEPENDENCIES} )
    message( "Finding external dependency: ${dependency}" )
    find_package( ${dependency} )
    # QUIET
    if ( ${dependency}_FOUND )
        message( STATUS "${dependency} was found at: ${${dependency}_DIR}" )
        if( NOT TARGET ${dependency} )
            add_custom_target( ${dependency} )
        endif()
        if( ${dependency} STREQUAL "Geant4" AND WITH_GEANT4_UIVIS )
            MESSAGE( "Finding Geant4 with vis and ui components enabled" )
            find_package( Geant4 REQUIRED vis_all ui_all )
            message( STATUS "The vis and UI components are enabled in Geant4." )
        endif()
    else()
        if( NOT INSTALL_DEPENDENCIES )
            message( FATAL_ERROR "${dependency} was not found and dependency installation is disabled.\nUse the option '-DINSTALL_DEPENDENCIES=ON' to enable automatic dependency installation." )
        else()
            message( STATUS "${dependency} was not found and will be installed as an external project." )
            include( Install${dependency} )
            set( DEPENDENCIES_NOTFOUND "YES" FORCE )
        endif()
    endif()
    add_dependencies( extdeps ${dependency} )
    
    # Debug print dep info if found
    if(${dependency}_FOUND)
        message("  ${dependency}_DIR=${${dependency}_DIR}" )
        message("  ${dependency}_VERSION=${${dependency}_VERSION}" )
        message("  ${dependency}_FOUND=${${dependency}_FOUND}" )
    endif()
    
endforeach()
